version: '3.8'

services:
  service:
      build: .
      ports:
        - '8000:8000'
      command: uvicorn --reload --host 0.0.0.0 --port 8000 main:app
      volumes:
        - .:/workspace:z
      depends_on:
        - postgres
      environment:
        DATABASE_URL: 'postgresql://postgres:postgres@postgres/recipe-api'

  postgres:
    image: postgres:13
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'recipe-api'